# Generated by Django 4.1.5 on 2023-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date_created',
            field=models.DateField(),
        ),
    ]
