# Generated by Django 4.1.5 on 2023-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_alter_blogmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
